create database config character set utf8 collate utf8_bin;

 CREATE TABLE config.OBJECT (
  ID INT NOT NULL AUTO_INCREMENT,
  NAME varchar(128) NOT NULL,
  PRIMARY KEY (ID)
 )ENGINE = InnoDB  DEFAULT CHARSET=utf8;
 
CREATE TABLE config.POSITION_RELATION (
  ID INT NOT NULL,
  OBJECT_TYPE INT NOT NULL,
  PARENT_ID INT,
  PRIMARY KEY (ID),
  FOREIGN KEY (ID) REFERENCES config.OBJECT (ID),
  FOREIGN KEY (PARENT_ID) REFERENCES config.OBJECT (ID) on delete CASCADE
 )ENGINE = InnoDB  DEFAULT CHARSET=utf8;
 
CREATE TABLE config.ADMINISTRATIVE_REGION(
	ID INT NOT NULL,
  	NAME varchar(128) NOT NULL,
  	ABBREVIATION varchar(64),
  	ZIP_CODE varchar(12) NOT NULL,
  	LONGITUDE double,
  	LATITUDE double,
  PRIMARY KEY (ID),
  FOREIGN KEY (ID) REFERENCES config.OBJECT (ID) on delete CASCADE
)ENGINE = InnoDB  DEFAULT CHARSET=utf8;

CREATE TABLE config.STATION_BASE (
  ID int(11) NOT NULL,
  NAME varchar(128) NOT NULL,
  CODE varchar(12) NOT NULL,
  LONGITUDE double DEFAULT NULL,
  LATITUDE double DEFAULT NULL,
  STATION_TYPE int(11) NOT NULL,
  SEQUENCE int(11) NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY (ID) REFERENCES config.OBJECT (ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE config.BUILDING(
	ID INT NOT NULL,
  	NAME varchar(128) NOT NULL,
  	CODE varchar(32) NOT NULL,
  	FLOOR_UNDERGROUND int(11) NOT NULL DEFAULT 0,
  	FLOOR_GROUND int(11) NOT NULL DEFAULT 1,
  	PRIMARY KEY (ID),
  	FOREIGN KEY (ID) REFERENCES config.OBJECT (ID) on delete CASCADE
)ENGINE = InnoDB  DEFAULT CHARSET=utf8;


CREATE TABLE config.FLOOR (
  ID int(11) NOT NULL,
  NAME varchar(128) NOT NULL,
  CODE varchar(12) NOT NULL,
  IS_ROOFTOP tinyint(1) DEFAULT 0,
  PRIMARY KEY (ID),
  FOREIGN KEY (ID) REFERENCES config.OBJECT (ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE config.ROOM(
	ID INT NOT NULL,
  	NAME varchar(128) NOT NULL,
  	CODE varchar(32) NOT NULL,
  	ROOM_TYPE INT NOT NULL,
  	SEQUENCE int(11) DEFAULT NULL,
  	PRIMARY KEY (ID),
  	FOREIGN KEY (ID) REFERENCES config.OBJECT (ID) on delete CASCADE
)ENGINE = InnoDB  DEFAULT CHARSET=utf8;

CREATE TABLE config.DOOR(
	ID INT NOT NULL,
  	NAME varchar(128) NOT NULL,
  	CODE varchar(32) NOT NULL,
  	SEQUENCE int(11) DEFAULT NULL,
  	PRIMARY KEY (ID),
  	FOREIGN KEY (ID) REFERENCES config.OBJECT (ID) on delete CASCADE
)ENGINE = InnoDB  DEFAULT CHARSET=utf8;
