create database config character set utf8 collate utf8_bin;

 CREATE TABLE config.OBJECT (
  ID INT NOT NULL AUTO_INCREMENT,
  NAME varchar(128) NOT NULL,
  PRIMARY KEY (ID)
 )ENGINE = InnoDB  DEFAULT CHARSET=utf8;
 
CREATE TABLE config.POSITION_RELATION (
  ID INT NOT NULL,
  OBJECT_TYPE INT NOT NULL,
  PARENT_ID INT,
  PRIMARY KEY (ID),
  FOREIGN KEY (ID) REFERENCES config.OBJECT (ID),
  FOREIGN KEY (PARENT_ID) REFERENCES config.OBJECT (ID) on delete CASCADE
 )ENGINE = InnoDB  DEFAULT CHARSET=utf8;
 
CREATE TABLE config.ADMINISTRATIVE_REGION(
	ID INT NOT NULL,
  	NAME varchar(128) NOT NULL,
  	ABBREVIATION varchar(64),
  	ZIP_CODE varchar(12) NOT NULL,
  	LONGITUDE double,
  	LATITUDE double,
  PRIMARY KEY (ID),
  FOREIGN KEY (ID) REFERENCES config.OBJECT (ID) on delete CASCADE
)ENGINE = InnoDB  DEFAULT CHARSET=utf8;

CREATE TABLE config.STATION_BASE (
  ID int(11) NOT NULL,
  NAME varchar(128) NOT NULL,
  CODE varchar(12) NOT NULL,
  LONGITUDE double DEFAULT NULL,
  LATITUDE double DEFAULT NULL,
  STATION_TYPE int(11) NOT NULL,
  SEQUENCE int(11) NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY (ID) REFERENCES config.OBJECT (ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE config.BUILDING(
	ID INT NOT NULL,
  	NAME varchar(128) NOT NULL,
  	CODE varchar(32) NOT NULL,
  	FLOOR_UNDERGROUND int(11) NOT NULL DEFAULT 0,
  	FLOOR_GROUND int(11) NOT NULL DEFAULT 1,
  	PRIMARY KEY (ID),
  	FOREIGN KEY (ID) REFERENCES config.OBJECT (ID) on delete CASCADE
)ENGINE = InnoDB  DEFAULT CHARSET=utf8;


CREATE TABLE config.FLOOR (
  ID int(11) NOT NULL,
  NAME varchar(128) NOT NULL,
  CODE varchar(12) NOT NULL,
  IS_ROOFTOP tinyint(1) DEFAULT 0,
  PRIMARY KEY (ID),
  FOREIGN KEY (ID) REFERENCES config.OBJECT (ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE config.ROOM(
	ID INT NOT NULL,
  	NAME varchar(128) NOT NULL,
  	CODE varchar(32) NOT NULL,
  	ROOM_TYPE INT NOT NULL,
  	SEQUENCE int(11) DEFAULT NULL,
  	PRIMARY KEY (ID),
  	FOREIGN KEY (ID) REFERENCES config.OBJECT (ID) on delete CASCADE
)ENGINE = InnoDB  DEFAULT CHARSET=utf8;

CREATE TABLE config.CABINET_COLUMNS (
  ID int(11) NOT NULL,
  NAME varchar(128) NOT NULL,
  CODE varchar(32) NOT NULL,
  SEQUENCE int(11) NOT NULL,
  CABINET_COUNT int(11) NOT NULL,
  CABINET_DEPTH double NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY (ID) REFERENCES config.OBJECT (ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE config.CABINET_MODEL (
  ID INT NOT NULL AUTO_INCREMENT,
  NAME varchar(128) NOT NULL,
  CODE varchar(32) NOT NULL,
  ABBREVIATION varchar(64),
  U1_POSITION tinyint(1) DEFAULT 0,
  U_COUNT int(11) NOT NULL,
  DEPTH double NOT NULL,
  MAX_USE_YEAR int(11) NOT NULL,
  PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE config.CABINET (
  ID int(11) NOT NULL,
  NAME varchar(128) NOT NULL,
  CODE varchar(32) NOT NULL,
  CABINET_MODEL int(11) NOT NULL,
  SEQUENCE int(11) NOT NULL,
  CABINET_DEPTH double NOT NULL,
  START_USE_DATE date,
  EXPECT_END_DATE date,
  PRIMARY KEY (ID),
  FOREIGN KEY (CABINET_MODEL) REFERENCES config.CABINET_MODEL (ID),
  FOREIGN KEY (ID) REFERENCES config.OBJECT (ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE config.POWER_STYLE(
  ID int(11) NOT NULL,
  LABEL varchar(80) NOT NULL,
  PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE config.POWER_PANEL(
  ID int(11) NOT NULL AUTO_INCREMENT,
  LABEL varchar(80) NOT NULL,
  NUMBER_OF_PORT int(11) NOT NULL,
  MAX_LOAD int(11) NOT NULL,
  PARENT_PANEL_ID int(11),
  FIX_POSITION int(11) NOT NULL,
  POWER_STYLE int(11) NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY (POWER_STYLE) REFERENCES config.POWER_STYLE (ID),
  FOREIGN KEY (FIX_POSITION) REFERENCES config.OBJECT (ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE config.NET_PANEL(
  ID int(11) NOT NULL AUTO_INCREMENT,
  LABEL varchar(80) NOT NULL,
  NUMBER_OF_PORT int(11) NOT NULL,
  FIX_POSITION int(11) NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY (FIX_POSITION) REFERENCES config.OBJECT (ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE config.VENDER (
  ID INT NOT NULL AUTO_INCREMENT,
  NAME varchar(128) NOT NULL,
  CODE varchar(32) NOT NULL,
  ABBREVIATION varchar(64),
  PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE config.MODEL (
  ID INT NOT NULL AUTO_INCREMENT,
  NAME varchar(128) NOT NULL,
  CODE varchar(32) NOT NULL,
  ABBREVIATION varchar(64),
  DEVICE_TYPE int(11) NOT NULL,
  VENDER int(11) NOT NULL,
  MAX_USE_DAY int(11) NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY (VENDER) REFERENCES config.VENDER (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE config.DOOR(
	ID INT NOT NULL,
  	NAME varchar(128) NOT NULL,
  	CODE varchar(32) NOT NULL,
  	SEQUENCE int(11) DEFAULT NULL,
  	PRIMARY KEY (ID),
  	FOREIGN KEY (ID) REFERENCES config.OBJECT (ID) on delete CASCADE
)ENGINE = InnoDB  DEFAULT CHARSET=utf8;
