create database portal character set utf8 collate utf8_bin;

CREATE TABLE portal.DEPARTMENT (
  ID INT NOT NULL AUTO_INCREMENT,
  NAME varchar(64) NOT NULL,
  PRIMARY KEY (ID)
 )ENGINE = InnoDB  DEFAULT CHARSET=utf8;

CREATE TABLE portal.DEPARTMENT_AREA_ASSO(
	DEPARTMENT_ID INT NOT NULL,
	ADMINISTRATIVE_AREA INT NOT NULL,
	PRIMARY KEY (DEPARTMENT_ID,ADMINISTRATIVE_AREA),
	FOREIGN KEY (DEPARTMENT_ID) REFERENCES portal.DEPARTMENT (ID),
	FOREIGN KEY (ADMINISTRATIVE_AREA) REFERENCES config.ADMINISTRATIVE_AREA (ID)
 )ENGINE = InnoDB  DEFAULT CHARSET=utf8;
 
CREATE TABLE portal.ACCOUNT_AUTHORIZATION(
	ID INT NOT NULL,
	NAME  varchar(64),
	AUTHORIZATION_GROUP INT NOT NULL,
	PRIMARY KEY (ID)
 )ENGINE = InnoDB  DEFAULT CHARSET=utf8;

CREATE TABLE portal.ACCOUNT_TYPE(
 TYPE_ID INT NOT NULL  AUTO_INCREMENT,
 TYPE_NAME  varchar(64) NOT NULL,
 DESCRIPTION varchar(255),
 PRIMARY KEY (TYPE_ID)
)ENGINE = InnoDB  DEFAULT CHARSET=utf8;

CREATE TABLE portal.ACCOUNT_TYPE_AUTHORIZATION(
	TYPE_ID INT NOT NULL,
	AUTHORIZATION_ID INT NOT NULL,
	PRIMARY KEY (TYPE_ID,AUTHORIZATION_ID),
	FOREIGN KEY (TYPE_ID) REFERENCES portal.ACCOUNT_TYPE (TYPE_ID)
 )ENGINE = InnoDB  DEFAULT CHARSET=utf8;

CREATE TABLE portal.PERSONNEL_CFG (
  ID INT NOT NULL AUTO_INCREMENT,
  NAME varchar(64) NOT NULL,
  E_MAIL varchar(64),
  TEL varchar(64),
  DEPARTMENT INT NOT NULL,
  ENABLE BIT NOT NULL,
  CREATE_TIME datetime,
  PRIMARY KEY (ID),
  FOREIGN KEY (DEPARTMENT) REFERENCES portal.DEPARTMENT (ID)
 )ENGINE = InnoDB  DEFAULT CHARSET=utf8;

 CREATE TABLE portal.ACCOUNT(
	ID INT NOT NULL,
	ACCOUNT varchar(64) NOT NULL,
	ACCOUNT_TYPE INT NOT NULL,
	LOGIN_PASSWORD varchar(64) NOT NULL,
	PASSWORD_TIME datetime NOT NULL,
	DEFAULT_THEME varchar(64),
	PRIMARY KEY (ID),
	FOREIGN KEY (ID) REFERENCES portal.PERSONNEL_CFG (ID),
    FOREIGN KEY (ACCOUNT_TYPE) REFERENCES portal.ACCOUNT_TYPE (TYPE_ID)
 )ENGINE = InnoDB  DEFAULT CHARSET=utf8;
 
 CREATE TABLE portal.DASHBOARD_ITEM(
 	ID INT NOT NULL,
 	TITLE varchar(64) NOT NULL,
 	HEIGHT INT,
 	URL varchar(64) NOT NULL,
 	PRIMARY KEY (ID)
 )ENGINE = InnoDB  DEFAULT CHARSET=utf8;
 
 CREATE TABLE portal.DASHBOARD(
	ACCOUNT_ID INT NOT NULL,
	DASHBOARD_ID INT NOT NULL,
	PRIMARY KEY (ACCOUNT_ID,DASHBOARD_ID),
	FOREIGN KEY (ACCOUNT_ID) REFERENCES portal.ACCOUNT (ID),
    FOREIGN KEY (DASHBOARD_ID) REFERENCES portal.DASHBOARD_ITEM (ID)
 )ENGINE = InnoDB  DEFAULT CHARSET=utf8;
 
  CREATE TABLE portal.ACCOUNT_PASSWORD_LOG(
    SEQUENCE INT NOT NULL AUTO_INCREMENT,
	ACCOUNT_ID INT NOT NULL,
	CHANGE_TIME datetime NOT NULL,
	NEW_PASSWORD varchar(64),
	OLD_PASSWORD varchar(64),
	PRIMARY KEY (SEQUENCE)
  )ENGINE = InnoDB  DEFAULT CHARSET=utf8;

